### PR TITLE
Create 3373_areatrigger_naxx.sql

### PR DESCRIPTION
**Pull request by QUADEMU**
After reporting of https://github.com/cmangos/issues/issues/2491 and investigations, i discovered the both areatriggers are attached for condition to one obsolet quest entry=9378 in "areatrigger_teleport" table, that don't have any sense and it's why after discussions with the author of issues i put for conditions the real needs for entrance,
the quests 9121 || 9122 || 9123 via the seldom used "conditions" table.

See you soon cMangos Community.

### CODE REVIEW

**Comment by ClassicW** [comment]
https://fr.classic.wowhead.com/quest=9121/naxxramas-la-citadelle-de-leffroi   
https://fr.classic.wowhead.com/quest=9122/naxxramas-la-citadelle-de-leffroi   
https://fr.classic.wowhead.com/quest=9123/naxxramas-la-citadelle-de-leffroi

**Comment by Tobschinski** [comment]
Nah, this is done with quest 9378 - the spell that should complete this quest for you when you turned in any of the attunement quests probably failed.

**Comment by ClassicW** [comment]
what version of the game are you testing on?

**Comment by ClassicW** [comment]
> Nah, this is done with quest 9378 - the spell that should complete this quest for you when you turned in any of the attunement quests probably failed.

what version of the game are you testing on?

**Comment by QUADEMU** [comment]
Will prepare the dumny def in spellscript for spell https://60.wowfan.net/en/?spell=28006

**Pull request closed without merging**
