### PR TITLE
Implement instance files in Classic-DB

### PR DESCRIPTION
**Pull request by MantisLord**
@cala @Tobschinski @Grz3s 

Ref: https://github.com/cmangos/issues/issues/1479

These files contain data which is nearly 1:1 with what's currently contained in Classic-DB as well as TBC-DB.

All guids, entries, and ids associated with dungeons/raids are moved to common ranges shared with TBC-DB with this update.

In the process of creating these files, I went ahead and did some comparisons to see what exactly is being added as new content here to Classic-DB. Here are my findings:

Shadowfang Keep
- 2 chests added to existing pooling
- Crate of Ingots (182011) gameobject removed - used for TBC+ paladin quest

Stockades
- pooling for chests added

Deadmines
- pooling for chests added

Wailing Caverns
- method of casting 13236 Nature Channeling changed - dbscripts/movement instead of creature_template_addon
- pooling for chests added

Razorfen Kraul
- missing movement added for guid 87394 id 4623
- pooling for chests added

Blackfathom Deeps
- pooling for chests added

Uldaman
- pooling for chests added
- some auras in template_addon added
- dbscript_string entry changed 2000005346->2000000430

Gnomeregan
- pooling for chests added
- aura 21862 in template_addon (maybe should be removed since it's in ACID too)

Sunken Temple
- pooling for chests added
- some creature linking added (none currently)
- aura 8876 in template_addon (maybe should be removed)

Razorfen Downs
- pooling for chests added
- some differences in template_addon auras

Scarlet Monastery
- pooling for chests added
- few extra entries in template_addon
- added spawn of 6490 Azshir the Sleepless
- gameobjects related to Hallow's End Headless Horseman event removed

Zul'Farrak
- movement for entry 10082 extended

Blackrock Spire
- pooling for chests added
- add 1 missing 9240 Smolderthorn Shadow Priest

Blackrock Depths
- minor template_addon differences

Maraudon
- more pooling for herbs added

Dire Maul
- pooling for chests and herbs added

Arathi Basin
- full rework: many npcs, objects, and lots of movement added

Temple of Ahn'Qiraj
- 20 Beetle (15475) added

------------------------------------------------------------------

I also figured it might be helpful to outline what the exact intended differences are between Classic and TBC are for these locations. If you were to diff these files with the files found in TBC-DB, here's what you would find:

Shadowfang Keep
- Landen Stilwell 17822 and Crate of Ingots 182011 removed

Scarlet Monastery
- scripts and gameobjects related to Hallow's End Headless Horseman event removed

Blackrock Depths
- The Tauren Chieftans, Brewfest, and Arena NPCs removed

Stratholme
- 17915 [PH] Invis Paladin Quest Credit removed
- scripts and 18 gameobjects removed for TBC Paladin quest

Ragefire Chasm
- content related to TBC+ only Paladin quest - The Path of the Adept 9692 removed

### CODE REVIEW

**Comment by cala** [comment]
Hi MantisLord,

Thank you very much for taking the time to do this PR. 

I was thinking to switch to this instance file system once I had caught up with TBC-DB, at last Classic DB release. I even wrote Python scripts to check the consistency of instances content before and after the switch and so far, the tests were good. 

That gave me the time to evaluate this system from an open source development point of view for a few months and to be very honest with you, I have second thoughts now.

The first thing that bother me is that flattening the instance data into a SQL dump file makes us lose the benefit of structured queries. For example, when updating lots of objects you are forced to manually update every INSERT line that needs it when only a few (if not a single) SQL queries would be enough.

Secondly, reviewability of commits is made harder because when one column of an INSERT statement is modified, reviewers have to count fields to understand which column was changed and it gets even harder when several are modified in a single line. Multiply this by the numbers of modified lines and things grow even harder to keep with. Also, reviewers have to deal with the dump structure of the SQL file, meaning that if a change affects different tables, a lot of scrolling may happen to clearly understand what is truly changed all over the file how individual changes are in fact related.
On the opposite, using SQL queries make pretty clear for reviewers which columns are edited and we also have the benefit of modifying several entries with a single query. It also allows to group related changes together and clarify them with dedicated comments.

Finally, flattening the structure is also a higher source of errors. Developers have to manually edit values right in the INSERT statements with the risk of editing the wrong column amongst the ten following empty values for example, each individual risk being multiplied by the number of edited lines.

I do understand and approve what was tried to be achieved with this change: easing backports by having a single file that would be almost copy-paste-able from one expansion to the other with a common GUID range. I like the idea but it has to face the fact that Classic content for TBC is not original Classic content + a few TBC-only additions. There was added content of course, but also removed content: specific ones like Scourge Invasion NPCs in instances but also common ones like many static spawns or patrols. For example,
If you take the content of LBRS in Classic DB, you have to remove many groups of trashes to get what it was in TBC times and even more were removed in WotLK. Thus, we can define a common GUID range for a given instance, but we will never achieve 1:1 GUID matching because mathematically speaking, we cannot define a proper transfer function between Classic and TBC as the two ensembles intersection does not fully contain one of the two ensembles. The best we can achieve is to define a GUID range that would be common but with loose GUID matching. 

We could think of including an export script in the repository to create on-the-fly the SQL dump so devs can have in one place all data related to an instance but I don't think we should use it as a development medium where actual changes take place.

**Comment by MantisLord** [comment]
@cala 

I understand and agree with most of your concerns with adopting this system into classic-db.

Do you think perhaps you could accept these files into classic-db as regular updates (not to be directly maintained/changed in the future)?

This way, we would at least share the same guids and ids for everything from this point going forward.
If we have to change things around in the future to account for some of the specific differences you pointed out, it would be much easier to do if we were "on the same page" so to speak.

**Comment by cala** [comment]
Hi,

First, all my apologies for long delay in reply. I have a bad tendency to delay complex things and handle easy ones first. Call this "quick win".

I fully agree with matching GUID range as much as possible. However, the TBC-DB and Classic-DB instances were updated many times since the opening of this PR and I still think that we will never achieve a 1:1. So I will close this PR for now and for the next Classic DB release, I will re-assign Classic DB instance GUID ranges to match as much as possible the values in TBC-DB. So we can have a fresh start.

**Comment by joao-fidalgo** [comment]
Well it's hard to achieve 1:1 when you let a PR like this get stale for so long.

**Comment by MantisLord** [comment]
I'll be putting us back to 1:1 shortly minus TBC content and the fixes/missing data I mentioned in my original post (mostly chest spawns/pooling data still not ported from tbc-db). Could create a fresh PR or update this one. I also have queries to verify/prove we're in sync.

In either case if we won't go the route of adopting the files in classic-db, we'll need to think about possibly dropping them in TBC-DB. If I had known we wouldn't be using them for other DBs, I wouldn't have ever added them. I assumed we were on the same page back when they were created after we had discussed (perhaps you weren't involved with that discussion @cala).

Having them only in TBC-DB only serves to make our original problem of differing guids way worse than it ever has been before (everything is different now).

**Comment by MantisLord** [comment]
>  I will re-assign Classic DB instance GUID ranges to match as much as possible the values in TBC-DB. So we can have a fresh start.

Also just a note about this... if the time comes when you find yourself trying to do this, look no further than the instance files in TBC-DB.... The work is already done for you there. If you start trying to manually reassign guids to match, you will go insane.
I challenge you to find some work which exists in classic-db for instance data that doesn't exist in those files. You will find only work missing from classic-db there.

**Comment by cala** [comment]
> Also just a note about this... if the time comes when you find yourself trying to do this, look no further than the instance files in TBC-DB.... The work is already done for you there. If you start trying to manually reassign guids to match, you will go insane.

Thanks, that was I wanted to do: use the TBC-DB GUID ranges as a basis to single out content that is in TBC and not in Classic (content added in TBC or commits that were possibly not ported yet) and what is in Classic and not in TBC (content removed in TBC or commits that were possibly not ported yet), though as you seem to be use some kind of script to compare the data, I guess missing commits in one way or the other should be very rare. 😄

**Pull request closed without merging**
