### PR TITLE
Create 1723_Q88Type.sql

### PR DESCRIPTION
**Pull request by bdebaere**
Princess Must Die! is not an elite quest

### CODE REVIEW

**Comment by cala** [comment]
I remember this being discussed at least twice and if the quest is still marked as elite, then *maybe* we got sources showing it as elite. I don't remember to be honest.
What tells you it is not? (just asking)

**Comment by Phatcat** [comment]
But Princess is not an elite mob? there are no elites involved in this? Aren't there only 1 elite quest in each starting zone? (the human one being Hogger)..

**Comment by Phatcat** [comment]
https://web.archive.org/web/20060615184820/http://wow.allakhazam.com:80/db/qlookup.html?zone=10

> Princess Must Die! 

> Wanted: "Hogger" (Elite)

Since Hogger is marked elite and Princess Must Die is not, it should be obvious now =)

**Comment by bdebaere** [comment]
What @Phatcat said: the quest does not involve killing elite mobs, which is what the marker signifies. Therefore at least to me, it should not be elite.

**Comment by cala** [comment]
> But Princess is not an elite mob? there are no elites involved in this? Aren't there only 1 elite quest in each starting zone? (the human one being Hogger).

I fully agree with this logic.

But there was a time were some quests were marked as "group", meaning you needed help to complete them. Some other were "elite", meaning you needed help against elite NPCs. Later, (I can't remember when), "group" was replaced by "elite" whatever the NPCs were elite or not. Then, Blizzard made some cleanup to the quests to fix "elite" quests with no elite NPCs involved. Hence my initial question.

But I think we can safely assume that at the time of patch 1.12.x, the clean up was already made.

**Pull request closed without merging**
