### PR TITLE
Create 1716_GO17713DoubleSpawn.sql

### PR DESCRIPTION
**Pull request by bdebaere**
Fix two crystals spawned exactly on top of eachother

### CODE REVIEW

**Comment by cala** [comment]
I have to either reject this one or ask you to do a lot of more work.

Let me explain. The reason is the two crystals GO *should* be spawned at the same place, but not at the same time. I mean, most if not all crystals GOs in Un'Goro crater should be pooled (any color should be able to spawn for one given spot, but only one at a time). Currently, the pools are missing and most of the spots have only one crystals spawned while there should be four of them (one red, one yellow, one blue, one green).
I never took the time to properly redo this. If you feel like handling this big one, I can provide direction. If not, I'll do it one day anyway.

**Comment by bdebaere** [comment]
Sure, I can do this, how can I reach you?

**Comment by cala** [comment]
I'm sorry, I have very little time to be on IRC lately and I'm leaving for holidays next week. So, I suggest the following approach : 
1. get the Go entry for each of the four colours of crystals from `gameobject_template` table
2. using those entries, search for all the unique spawn positions for the crystals (ignore duplicates, that's the job of pools) in `gameobject` table
3. remove all entries of the crystals from `gameobject` table
4. for each spawn position:
    - spawn all four crystal GOs (one red, one yellow, one blue, one green)
    - create a new `pool_gameobject` with these four GUIDs (set chance to 0, so they have equal chance to spawn)
    - create a new `pool_template` using the pool entry used for the four crystal GOs and limit the max spawn to 1
    - rince and repeat

You should have as many `pool_template` entries as initial spawn positions. It would be probably helpful to write a small script to do this, though it is doable by hand.

If you have any questions, I'll be happy to answer them.

**Comment by Tobschinski** [comment]
> spawn all four crystal GOs (one red, one yellow, one blue, one green)

Is that correct? Check the wowhead maps for each crystal, you will notice something interesting.

**Comment by cala** [comment]
Oh my... That's gonna give me a headache. Forget what I wrote... This gonna be extra complicated to do clean things without proper sniff data.
Just pool together these two GOs instead of removing one, and we're done.

Thanks @Tobschinski

**Pull request closed without merging**
