### PR TITLE
[ACID] "classic-zones" - RangeMode AI

### PR DESCRIPTION
**Pull request by AnonXS**
Conversion of Dynamic Movement cases to new RangeMode AI

- Related Core Commit https://github.com/cmangos/mangos-classic/commit/f1a8afac7fc2c07eefceddcdf06ebd010d7cea58

### CODE REVIEW

**Comment by cala** [comment]
Thank you for sharing. Same question that for initial update from killerwife: were these changes made with the actual acid-classic.sql as a source or were they ported from acid-tbc.sql file?

**Comment by AnonXS** [comment]
tbc-db port and i tryed my best to spot all differences that are included in classic version of acid. e.g
```
-- Blackwing Mage 12420 (MODIFIED FOR 1.12.1) - ARCANE EXPLOSION PROC HAVE BEEN CHANGED TO MANUALLY PROCED SPELL
('1242001','12420','11','0','100','0','0','0','0','0','0','0','11','35187','0','0','0','0','0','0','0','0','0','0','Blackwing Mage - Cast Arcane Explosion Proc on Spawn'),
('1242002','12420','4','0','100','0','0','0','0','0','0','0','57','1','35','0','0','0','0','0','0','0','0','0','Blackwing Mage - Enable Caster Mode on Aggro'),
('1242003','12420','0','0','100','1025','7000','12000','12000','16000','0','0','11','22271','17','0','0','0','0','0','0','0','0','0','Blackwing Mage - Cast Arcane Explosion'),
('1242004','12420','9','0','100','1025','0','40','3400','4800','0','0','11','17290','1','256','0','0','0','0','0','0','0','0','Blackwing Mage - Cast Fireball'),
```

**Comment by cala** [comment]
Thanks for clarifying, :+1: 
That was my first concern.

When ACID was still separated from DB, Classic scripts were basically copy-paste of TBC ones. I spent a lot of time cleaning up spells IDs, event flags and some scripts for NPCs that had their skills changed from Classic to TBC, as you noticed. Remaining event flags and spell IDs can still be spotted via smart SQL queries or error logs, but scripts changes will be harder to spot on but there shoud not be many of them.

My second concerns is about keeping both versions on level. Actual acid-classic.sql includes updates from acid-tbc.sql up to some point in June or July. My local branch includes updates up to early August. Thus, I'd like to know if I need to sync with TBC-DB from June to nowadays or if the file you are pushing also includes all changes you made in the meantime and to which point in time.

**Comment by cala** [comment]
Merged, thanks ! :+1: 

@killerwife @AnonXS awesome work with this new EventAI upgrade and scripts updates! Congratulations!

**Pull request closed without merging**
