### PR TITLE
[3295] Dust Devil visibility distance fix

### PR DESCRIPTION
**Pull request by vdeschuyf**

### CODE REVIEW

**Comment by killerwife** [comment]
I hate to say this, but visibility was taken from classic if I recall correctly. @Kittnz might know

**Comment by vdeschuyf** [comment]
Sorry for the misunderstanding, but do you mean classic (2006) or the _new_ classic (2019)?
I would be surprised if visibility for such an ordinary mob from so far away wouldn't mentioned on any of these sites:

-  https://classic.wowhead.com/npc=832/dust-devil#comments

- https://classicdb.ch/?npc=832#comments

**Comment by killerwife** [comment]
It came from a db2 of some version, i.e. complete data for all npcs.

**Comment by killerwife** [comment]
Ok, checked classic. this is a valid change across all 3 dbs. I will let cala merge this.

**Comment by vdeschuyf** [comment]
Thank you! <3

**Comment by cala** [comment]
Merged, thank you very much !

**Pull request merged**
