### PR TITLE
Change the DB default schema name to reflect repository

### PR DESCRIPTION
**Pull request by killerwife**
Accompanies a core commit.

### CODE REVIEW

**Comment by cala** [comment]
Thank you. I will merge this for consistency with core and other DBs, but in my opinion `mangos-classic` would have been a better naming (matches core repository's name) than `classicmangos`. I think we should even assume the CMaNGOS name by using `cmangos-classic` instead.

@cyberium what do you think?

**Comment by killerwife** [comment]
I used version first, so that in windows, i can see the 3 (or 4) groups right next to each other, so when devving, classicmangos, classicrealmd and classiccharacters is next to each other. This is good since I do a lot of version hopping when helping you guys. The cmangos vs mangos is an oversight on my end. Imo we should already be cmangos-classic on the core end.

**Comment by cyberium** [comment]
Yes i plan to rename them all anyway in some future. Probably the best time for it is when i'll push the new standalone AuthServer for all core. As it will need some DB adjustement.

**Comment by cala** [comment]
Cool. Merged, thanks! :+1:

**Pull request closed without merging**
