### PR TITLE
Create 1879_forceFieldRename.sql

### PR DESCRIPTION
**Pull request by bdebaere**
The name 'forcefield' without a capital letter looks a bit unprofessional when hovering over it with the mouse in game.
Updated the name to Forcefield with a capital F, like entry 180497.

### CODE REVIEW

**Comment by Tobschinski** [comment]
forcefield is correct

**Comment by bdebaere** [comment]
@Tobschinski Should the name appear when mousing over it? Sometimes a game object does not show its name.

**Comment by Tobschinski** [comment]
flags and faction is also correct, shouldn't be visible for regular players

**Comment by bdebaere** [comment]
@Tobschinski Thanks!

**Pull request closed without merging**
