### PR TITLE
fix Update folder structure

### PR DESCRIPTION
**Pull request by Phatcat**
should address that we have two folders, update and Update. should just be Update, right? @cyberium @cala

### CODE REVIEW

**Comment by Phatcat** [comment]
>  100755 → 100644 

what's that about ?

**Comment by cyberium** [comment]
Yes i already warned -> https://github.com/cmangos/classic-db/commit/637b3f28c4d8b0adb2016898bbd6f8333f5655d9
They have probably to git reset --hard to remove 'updates' folder.

**Comment by Phatcat** [comment]
Yeah, I didn't think far enough to realize that this commit only moves the misplaced updates, it doesn't actually remove the folder as well... not sure how to do that on windows where uppercase and lowercaser is ignored in the folder structure. the only way I was able to do this was do one commit where I first moved all updated to another folder, deleted both update folders, then did another commit where I moved them all into a new Updates folder and removed the temp folder, then I squashed the two commits and here we are.

**Comment by cala** [comment]
> 100755 → 100644
> what's that about ?

It is a permission change of the SQL files. By default, my OS sets +x permission on SQL files (do not ask why) while Windows does not. These changes are harmless and can be safely ignored.

> They have probably to git reset --hard to remove 'updates' folder.

I do not have the `updates` folder anymore since @cyberium renamed it:
folder structure

So, I don't know what more I can do... I agreed to this change because it was supposed to be harmless. But if we are spending days on fixing this, I think our energy would be better used elsewhere...

**Comment by cala** [comment]
Merged.
Hopefully fixed.
Thank you.

**Pull request merged**
