### PR TITLE
Update health and mana multipliers for all creatures.

### PR DESCRIPTION
**Pull request by ratkosrb**
Updates for all creatures that had wrong health or mana multipliers as requested by cala. This data is sent by the server in 1.13 and is even saved in the cache. Credits to kittnz and modox for their help to gather it.

### CODE REVIEW

**Comment by cala** [comment]
Yeah! Thank you very much. :+1:

**Comment by cala** [comment]
I had a first look at these multipliers yesterday evening and I noticed that some NPCs in this list are already considered as fixed in Classic DB with HP/mana values matching WoW Bestiary.
Example:
```
NPC 4802 (Blackfathom Tide Priestess)
Rank: Elite
Current DB PowerMultiplier: 2.0 (min/max mana perfectly match values in Bestiary)
Sniffed PowerMultiplier: 2.5
```

This means that either:
1. the Bestiary is wrong
2. the Bestiary is correct for patch 2.3 but the multipliers for these NPCs were changed since Classic
3. the values from new WoW Classic were updated and are thus different from the original ones

In my own opinion, I would pick point 2 as an explanation because I see no reason for Blizzard to slightly rework creature health/mana multipliers for a few dozen of NPCs and not the others since original Classic. While it would make sense that they adjusted some multipliers when they dumbed down a lot of Azeroth NPCs in patch 2.3 to ease leveling.

Unfortunately this means that multipliers can change from one expansion to another without the NPC changing their rank (elite -> normal) and that we now have to be cautious when setting a multiplier for a NPC based on sniffs from a later expansion.

Before merging this (and thus overriding some values that are already considered as correct, possibly wrongly), I'd like to also have opinion from @killerwife @AnonXS @Tobschinski 

Thanks!

**Comment by ratkosrb** [comment]
Option 3 seems out of the question to me, considering Blizzard developers called the original 1.12 data sacrosanct. If they would have changed anything, it would have been buffing the raid bosses, not lvl 20 mobs, but they didn't change anything.

**Comment by ratkosrb** [comment]
Also I want to mention that while updating health of creatures on vmangos based on the multipliers (we don't have cls implemented), I noticed that the calculated value was clearly wrong for some creatures that were summoned by spells.

For example Unstoppable Abomination (16428) should have 97000 health, but has a health multiplier of 1. So spell 28422 must be setting the health when summoning the creature.

**Comment by cala** [comment]
I also doubt they changed NPCs stats in new Classic.

In my opinion, option 2 is the right one but I'd like to hear from other before doing such a change.

**Comment by cala** [comment]
@ratkosrb with these multipliers changes and the following updates of HP/mana values, the number of NPCs with incorrect stats in the database drops from 4950 down to 1394.

If you can confirm that all NPCs in the database (except the ones in your PR of course) have correct HP and mana multipliers (i.e. the same as current Classic), I would also be able to fix the remaining 1394 ones.

**Comment by ratkosrb** [comment]
This pull request includes only updates for creatures that had a wrong multiplier, as it makes no sense to update it for creatures that already have the same multiplier. Unfortunately damage and armor multipliers are not sent in this packet, so I can't tell you if any creatures have wrong values for those.

**Comment by ratkosrb** [comment]
Also there are 1265 creatures that do not exist in your database at all, so I did not include health and mana update queries for them. These appear to be unused npcs and test creatures (a lot of them have [Unused] and [PH] in the name).

**Comment by ratkosrb** [comment]
And obviously it does not include updates for custom and tbc creatures. You have 13 of those in classic-db.

Untitled

**Comment by cala** [comment]
> This pull request includes only updates for creatures that had a wrong multiplier, as it makes no sense to update it for creatures that already have the same multiplier.

Thank you. This means that I can fix the remaining NPCs by using the CLS as their multipliers already match retail.

> Unfortunately damage and armor multipliers are not sent in this packet, so I can't tell you if any creatures have wrong values for those

I know. This is the biggest issue when fixing NPCs stats and the Bestiary is extremely helpful in that though we cannot fully rely on it.

> Also there are 1265 creatures that do not exist in your database at all.

Thank you for pointing this. I think we will need to have a look at them at some point or another because I highly suspect that dummy NPCs involved in some spells mechanics (in AQ40 or Naxxramas for instance) are currently missing from our database.

> For example Unstoppable Abomination (16428) should have 97000 health, but has a health multiplier of 1. So spell 28422 must be setting the health when summoning the creature.

This is weird. Looking at the spell, there doesn't seem to be anything that could be used as a multiplier for Hit Points. This means that either the sniffed healthmultiplier is wrong because Naxx is not yet released (I doubt this as other unreleased summoned NPCs do not have this issue) or the health upgrade is applied by script or through an aura. Like many strange things in original Naxxramas, we will probably have to wait for the content to be released and sniffed for a better understanding. I will also rework Kel'Thuzad encounter soon, that will be a right moment to dig this specific issue.

**Comment by cala** [comment]
@ratkosrb I don't want to abuse your time but would it be possible that you share the data for the 1265 NPCs missing from our database, please?

I'm 98% certain we are missing spell triggers/targets from Naxxramas (and possibly elsewhere) in our database and I need them to properly re-script bosses there.

If it is easier for you, a simple dump from your own SQL table will be enough and I'll do the import structure adjustments by myself.

**Comment by AnonXS** [comment]
https://classic.wowhead.com/npc=1265/rudra-amberstill ?

**Comment by cala** [comment]
I'm sorry, but I don't get your point regarding this NPC.

**Comment by ratkosrb** [comment]
Sure, I'll submit them.

**Pull request merged**
