### PR TITLE
More gameobject template updates.

### PR DESCRIPTION
**Pull request by ratkosrb**
Update more data for gameobjects based on wdb cache from classic. Also update data1 and data6 fields to be signed, since some entries have negative values in them. They are signed in Trinity's database too.

### CODE REVIEW

**Comment by cala** [comment]
Thank you. I'm currently looking at this.

Regarding the type change for `data1` and `data6`, if this is easy to do for the database and database loader, however the GameObject code assumes in several places that these fields are unsigned. Can all objects have a negative value for these fields or only some of them (and then: which ones)? Thus, I can update the core code accordingly.

**Comment by ratkosrb** [comment]
In `data1` i see negative values for type 10. In `data6` i see a negative value for one object of type 6. This is from classic wdb files.

In the Trinity database, there are negative values in `data1` for types 10 and 22, and in `data6` for types 0, 2, 3, 5, 6, 7, 8, 9, 10, 11, 14, 17, 19, 21, 22, 23, 25, 30, 32, 33, 34.

**Comment by cala** [comment]
Thank you very much for this quick answer. As this change in Classic core will also be ported to TBC and WotLK ones, I'll consider all possible concerned GameObject types.

And what does a negative value means in your opinion? Is it always -1?

**Comment by ratkosrb** [comment]
In my data from classic wdb, all the negative values for `data1` are -1. In `data6` there is only one negative value and its -65536.

**Comment by cala** [comment]
Thanks alot! :+1:

**Comment by cala** [comment]
I'm nearly finished with Kel'Thuzad encounter (and thus, Naxxramas rework). Next, I intend to merge many of the PRs in database and core and I want to be sure to do this one properly as even if it is not hard code-wise, secondary effects can be heavy if we do not handle the data properly.

**Comment by cala** [comment]
Merged in https://github.com/cmangos/classic-db/commit/2f7c921d1fcdfa22d7b184d35a872117edd8ae43
Thank you very much. 👍

**Pull request closed without merging**
