### PR TITLE
Love is in the Air Revamp

### PR DESCRIPTION
**Pull request by Zingzah**
This pull request aims to fix several issues that currently exist with the Love is in the Air festival on Cmangos Classic.  Currently the state of the event provides no functionality associated with npc interactions, quests and items to complete any activities that comprise this event. Specificallt this includes:

1. Innkeepers do not stock any event items or provide any information on the event to players
2. Guard and civilian npc do not provide gossip interactions to obtain any of the necessary items for the event.
3. Kwee is not spawned anywhere
4. Questline is broken and does not progress correctly.
5. Final quest hand-in is not scripted
6. Spells/items not functional(nf)/behaviour issues i.e. Candy bag(nf), silver shafted arrow(nf), love fool(follows player instead of remaining stationary)

This PR aims to correct these issues or highlight issues unable to be corrected.  Along with screenshots, web pages and videos as refences, the following assumptions have been made:

Buff/debuff priority: Love token > perfume/cologne > heartbroken

City gifts are given based on faction rather than race.  Some npcs have a city faction different than one associated with their race.  e.g. npc with dwarf model has stormwind faction or tauren model with orgrimmar faction.  These are uncommon and for the most part the model will align with the faction of the npc.

There wasn't enough evidence to conclusively assign civilian and guard gossips so some of this is guesswork.  Missing tauren and troll racial gossips need to be located probably.  Placeholders (tauren, troll, goblin) have been put in place until better information is found. Others races have been matched to a reasonably obvious gossip that characterises the particular race.

Heartbroken to gift ration set at 1:6.  Can change this to another ratio for exact data.

Civilians have been classified as vendors, questgivers and npcs that have no known purpose.  Trainers and npcs with specific gossips were not candidates for gift giving duties. This due to having to assign a complete gossip menu for each of these as well as obscuring the original gossip which could contain necessary information for players be they new or otherwise.  Stormwind was an exception where generic gossip was present for all vendors in a specific quarter.  In this case these vendors were candidates for civilian gift giving. Npcs known to involved with scripts were also not considered candidates.

Guards were divided into two groups, those that were of one gender(Dwarves, Sentinels) or no gender(Undercity) and those with two genders(Stormwind, Thunderbluff and Orgrimmar).  One gender guards gossips could be handled through the DB whereas the two gender guards had to be handled through SD2.  Npcs unlike players, don't have gender.  They only have modelids that show gender.  There is no DB condition to check for modelid and so the gossip menus for these two gendered guards had to be manually scripted in sd2 incorporating the modelid condition check for offering a male or female gossip response.

There various valentine spells (8) were arbitrarily assigned as follows:

1 spell for each city guards
1 spell covering alliance civilians
1 spell covering horde civilians

The two questlines were also corrected with dependencies and next quests properly organised.  However, the final quest given by the fragrant cauldron was unavailable(gm mode shows available) having met the correct requirements so a suspected incorrect lock value for the gameobject could be the problem in fixing this issue. Scripting of The Source Revealed quests between Stafford and Annalise Lerent has also been implemented.

Due to lack of any exact data Kwee spawns were estimated from screenshots.
Heart Candy spell was added to core.

References:
http://world-of-warcraft.alteredgamer.com/wow-achievements/45389-world-of-warcraft-holiday-event-achievements-love-is-in-the-air/#imgn_0
http://casualwow.blogspot.com.au/2007/02/love-is-in-air-decorations.html
http://casualwow.blogspot.com.au/2007/02/love-is-in-air-two-things-i-didnt-know.html
https://casualwow.blogspot.com.au/2007/02/love-is-in-air-get-thee-to-kwee.html?m=0
http://www.techrepublic.com/pictures/making-love-in-the-world-of-warcraft/
http://wowwiki.wikia.com/wiki/Strange_Winged_Goblin
http://www.wowhead.com/npc=22239/strange-winged-goblin#comments
https://www.wow-freakz.com/npc_finder.php?npc=22239&name=strange-winged-goblin
https://web.archive.org/web/20070213054629/http://www.wowwiki.com/Love_is_in_the_Air
http://wowwiki.wikia.com/wiki/Love_is_in_the_Air_2009
http://www.wowhead.com/quest=8993/gift-giving#comments
http://casualwow.blogspot.com.au/2007/02/there-is-no-love-in-exodar-or.html
https://www.engadget.com/2007/02/13/guards-bugged-in-silvermoon-city/
http://wow.gamepedia.com/Pledge_of_Adoration
http://wow.gamepedia.com/Pledge_of_Friendship
http://wow.gamepedia.com/Gift_of_Adoration
http://wow.gamepedia.com/Gift_of_Friendship
http://wowwiki.wikia.com/wiki/Stormwind_Guard%27s_Card
http://wowwiki.wikia.com/wiki/Undercity_Guardian
http://wow.gamepedia.com/Guardian%27s_Moldy_Card
https://www.engadget.com/2009/02/10/the-overachiever-completing-fool-for-love/ Coldara Dean gossip photo
http://www.wowhead.com/quest=8980/zinges-assessment -- wowwiki, wowpedia wrong.  Not a choice of rewards. same for 9025.
http://www.pcgames.de/World-of-Warcraft-Wrath-of-the-Lich-King-Spiel-42979/Specials/World-of-Warcraft-Liebe-liegt-in-der-Luft-704467/galerie/1245983/
http://www.buffed.de/World-of-Warcraft-Spiel-42971/Videos/Wow-Show-13-797600/
https://wow.gamepedia.com/Bouquet_of_Red_Roses
https://www.engadget.com/2007/02/13/sex-in-the-undercity-a-guide-to-finding-love-in-azeroth/

### CODE REVIEW

**Comment by cala** [comment]
Thank you for this PR, well documented as usual!
As usual, I'll do my best to review and merge it before the event starts again. ;-)

**Comment by Zingzah** [comment]
Nps Cala. Here is also an album of screenshots from the event - https://www.flickr.com/photos/138109710@N06/albums/72157666129156199.  There's a corresponding PR for the core to add support for some spells and gossips. PR 323 in mangos-classic.

**Comment by Zingzah** [comment]
The changes to DB for the guards gossips have now been added for Thunderbluff, Orgrimmar and Stormwind.  These changes move this functionality from SD2 to the DB with changes to the core which adds a gender check for NPCs.

**Comment by cala** [comment]
@Zingzah 
Greetings,

A few things:
- first, I only log in recently in Discord so I only got your message there. I'll try to catch you soon to discuss this
- I apologize, I failed to review this PR (and the core one) before the event starts again : I spent far more time than I thought in reworking BWL and Lunar Festival. I'm starting to look at this PR right now

**Comment by Zingzah** [comment]
Nps Cala.  It is a large PR and the changes weren't submitted in a timely manner for you to review.  BWL and Lunar Festival improvements look great and appreciate all the work in the 1.9 release.

**Comment by cala** [comment]
Ok. I had a first look at this PR and there are *a lot* of things in it. As I have a very genuine knowledge of this event, I need to read your sources to understand what is in this event and how it should work.

**Comment by killerwife** [comment]
@cala there is Love is in the Air on retail right now. Any data you need gathered? If possible, be quick about it.

**Comment by cala** [comment]
The event changed a lot in 2009, so I'm afraid there is little thing that would require sniff for Classic and that are still available. My only idea would be about how the gender gossip is handle as there seems to be some uncertainty on this topic. But nothing else comes to mind right now.

**Comment by cala** [comment]
To do list for this event based on the PR:
- [ ] Innkeepers do not stock any event items or provide any information on the event to players
- [ ] Guard and civilian npc do not provide gossip interactions to obtain any of the necessary items for the event.
- [ ] Kwee is not spawned anywhere
- [ ] Questline is broken and does not progress correctly.
- [ ] Final quest hand-in is not scripted
- [ ] Spells/items not functional(nf)/behaviour issues i.e. Candy bag(nf), silver shafted arrow(nf), love fool(follows player instead of remaining stationary)

**Comment by cala** [comment]
First part merged in: https://github.com/cmangos/classic-db/commit/057d7f3377768821c6556bfd9e0f33c231fdb3e7
I'm truly ashamed of myself for taking this long before looking at this nicely done and well documented PR.

**Comment by Tobschinski** [comment]
Yeah, you should be.

**Comment by Levitanious** [comment]
...it only took almost two years, after all. `</joke>` `<3` Thanks for the work, all of you.

**Comment by cala** [comment]
Kwee was added in https://github.com/cmangos/classic-db/commit/e22e5ad4a80151d9a4be75c611668a7f2f1693fe and https://github.com/cmangos/classic-db/commit/bf03a9ccd8c7b282db5bf6f572f03d9d2e63d368

**Comment by cala** [comment]
Quest chaining and final quest scripting in https://github.com/cmangos/classic-db/commit/1232fbd23162843145d2be41b6baf7ab0c7a899d

**Comment by cala** [comment]
City guards gossips are in https://github.com/cmangos/classic-db/commit/be483825c54a68cabd3acff5467978ec82e2ecbf

**Comment by cala** [comment]
All merged! Thank you very much!

**Pull request closed without merging**
