### PR TITLE
Children's Week Fixes

### PR DESCRIPTION
**Pull request by Zingzah**
This PR aims to correct issues present with the Children's Week event.  As the event currently stands on classic there are several erroneous/non-functioning features including
- Incorrectly equipped and spawned orphans in both Orgrimmar and Stormwind
- Missing gossips for orcish orphans
- Matrons being spawned only during the Children's Week Event
- Incorrect quest texts in several cases
- Mr Wiggles having an incorrect model
- Curmudgeon's sack having no gold in it (gasp!)
- Cairne Bloodhoof having incorrect gossip option
- Orphan questline for both horde and alliance not completable due to incorrect progression
- Discovery quests not completable due to no database or core support

**Alliance Questline**

             1687 
1468---1558--558+4822-----171
             1479
Completing 1468(Children's Week Alliance) makes available quests 1687(Spooky Lighthouse), 1558(Stonewrought Dam) and 1479(Bough of the Eternals).  Completion of all of these quest makes available 4822(You Scream, Ice Cream) and upon selecting this quest 558(Jaina's Autograph) becomes available.  Both 4822 and 558 should become available simultaneously but due to the limitations of Next/Prev Quest ID this was the only workaround that could be reached.  After both 558 and 4822 are completed, the final quest in the chain 171(Ward of the Alliance) becomes available.

**Horde Questline**
          910
172--911-----915+925---5502
         1800

The Horde questline takes the same approach with corresponding quests. Again 915(You Scream, Ice Scream) needs to taken to make available 925(Cairne's Hoofprint) for the same reasons as in the alliance questline.

There is already a SD2 PR pending(#244 in Cmangos-classic) which adds support for the orphan discovery quests and coupled with the DB additions in this PR, will make these quests completable in the correct way.

These issues are corrected and provide a functional Children's Week event.  
References:
http://web.archive.org/web/20061117203721/http://www.wowwiki.com/Children's_Week
http://web.archive.org/web/20080510103746/http://www.mortalken.com/seasons/childrensweek
http://www.wowhead.com/quest=1468/childrens-week#comments
http://www.wowhead.com/quest=172/childrens-week#comments
http://www.wowhead.com/quest=1687/spooky-lighthouse
http://www.wowhead.com/quest=1558/the-stonewrought-dam#comments
http://www.wowhead.com/quest=1479/the-bough-of-the-eternals
http://www.wowhead.com/quest=910/down-at-the-docks#comments
http://www.wowhead.com/quest=911/gateway-to-the-frontier
http://www.wowhead.com/quest=1800/lordaeron-throne-room

### CODE REVIEW

**Comment by Zingzah** [comment]
Sorry, my little diagrams didn't work in posting(they looked ok in editing).  Just disregard and read the description to avoid any confusion

**Comment by Muehe** [comment]
```
           1468
            |
     -------+-------
    |       |       |
    1687   1558   1479
    |       |       |
     -------+-------
            |
         ---+---
        |       |
      4822     558
```

Like so?

Btw. limitations to the quest relation system are tracked in https://github.com/cmangos/issues/issues/1140, @killerwife is working on it...

**Comment by Zingzah** [comment]
Ty Muehe for the info and much better questline diagram :)

**Comment by killerwife** [comment]
@Muehe the conditioning system was implemented. Using that you can do anything you want.

**Comment by cala** [comment]
Merged in https://github.com/cmangos/classic-db/commit/aed090a16e8502e482ab970e9bc7611e4803ba3b
Thank you !

**Pull request closed without merging**
