### PR TITLE
1704_KorKronElitesRemoveEliteRank.sql

### PR DESCRIPTION
**Pull request by bdebaere**
Kor'Kron Elites should not be elite
See
https://youtu.be/YcEqpVfrE7U?t=55m43s
http://www.wowhead.com/npc=14304/korkron-elite#comments
Patch 2.4.3 "Strangely enough, they aren't Elite."

### CODE REVIEW

**Comment by brotalnia** [comment]
Same case for Deathguard Elite, I don't know if it has been already changed though.

http://www.wowhead.com/npc=7980/deathguard-elite#comments
"It's funny how they aren't elite."

**Comment by bdebaere** [comment]
Do you have any video/other sources for this? The comment you linked is patch 3.0.3 unless I'm not viewing it correctly.

**Comment by brotalnia** [comment]
Why would they randomly make undead guards in Tirisfal non-elite in 3.0.3? Makes more sense that they both were not elite from the beginning.

In this video you can see him mouse over the guard and it doesn't say elite in the tooltip.
https://youtu.be/8glOVdqo3hI?t=46m26s
deathguard elite

But it should say it if he was elite. Here's a screenshot from mangos.
deathguard non elite


The big guards in Undercity were also not elite - https://youtu.be/D9O903Wnmb4?t=20s

**Comment by bdebaere** [comment]
I realize that it makes sense, but it's always nice to have a source if available. I'll make the adjustment.

**Comment by bdebaere** [comment]
https://github.com/cmangos/classic-db/pull/68

**Comment by Tobschinski** [comment]
Do you have a video showing them hostile towards any player? Changing the rank is not enough, they'd still hit as hard as elites.

**Comment by bdebaere** [comment]
I don't myself I'm afraid.

**Comment by Tobschinski** [comment]
Okay, I'll just assign some generic multiplier then.

**Comment by bdebaere** [comment]
Can you share the multiplier, so I can adjust the queries please?

**Pull request closed without merging**
