### PR TITLE
Create 1857_WinterVeilCookieSpellEffect.sql

### PR DESCRIPTION
**Pull request by bdebaere**
Add the missing matching Well Fed spell effect to the Winter Veil Cookie spell.

### CODE REVIEW

**Comment by bdebaere** [comment]
Please do note that there is something still wrong with this spell effect itself. At the moment it only increases my Stamina and Spirit by 6 for a level 59 character. It should be around 14.

**Comment by bdebaere** [comment]
This also fixes the Bobbing Apple as it is the same spell used.
https://github.com/cmangos/issues/issues/19
(https://github.com/cmangos/issues/issues/1496)

**Comment by cala** [comment]
This needs to be investigated. I'm not sure this is the correct way to fix this because TBC and WotLK DBC have the same Effect2=0. So, we are probably missing something there (an additional spell or effect linked or proc'ed) when this spell is cast.

**Comment by cala** [comment]
I had a deeper look at your fix and all the other related spells and I think you approach is the only acceptable unless we want to add an ugly spell exception into the core. I'll merge it soon into the core.

But before that:

> Please do note that there is something still wrong with this spell effect itself. At the moment it only increases my Stamina and Spirit by 6 for a level 59 character. It should be around 14.

Those values are consistent with what is in the spell DBC (from Classic to WotLK): a flat 6 for spirit and 10% of the level + 1 for stamina (so roughly 6 at level 59). The question is: who is right, the spell description or the spells values? Based on the various comments I just read, I think we should trust the tooltip, which means this spell's template also needs to be fixed...
I'm also on it.

**Comment by cala** [comment]
Merged in https://github.com/cmangos/mangos-classic/commit/7542662e02a671667f2c363f89ab798e096c72a3
Thank you!

**Pull request closed without merging**
