### PR TITLE
Complete Overhaul of Mining Node Data

### PR DESCRIPTION
**Pull request by Sneakyabc**
I noticed that the spawning on mining nodes in Durotar and The Barrens seemed wonky, so I have spent the last several months working on a total overhaul of the placement of all of the gameobjects and their pooling data for Kalimdor and the Eastern Kingdoms.

I've split this into 3 parts:
4494) Remove all of the old data, including gameobject entries, pooling data, and the spawn_group table entries for random nodes throughout Kal/EK 
4995) Insert gameobject and pooling data for EK (map 0) 
4996) Insert gameobject and pooling data for Kal (map 1)

Data for dungeons/anything outside of kalimdor/eastern kingdoms was untouched. I DID pay attention to the weird, alternative entries for nodes in certain zones (such as The Barrens, Redridge Mountains, Felwood, etc.) so hopefully I did not miss anything.

The spawning of mining nodes should be much more blizzlike now I believe. The Barrens before my changes only had about 20-30 mining nodes despite it being a huge zone, and the pooling of the nodes that were there was very clearly wrong.

I got the locations of each node from WoWhead and the pooling and spawn chances (% chance a rare node like Silver or Gold will be chosen) were mostly guesswork but I do not know how or where I'd find a reliable source on those numbers.

This will insert/change about 22,000 rows of data in the database, so hopefully this rework is solid and welcome. I built a tool to help visualize the placement and pooling of the nodes in each zone, without which this task would've probably been impossible. I'm guessing that's why nobody had done something like this previously. Here's the repository I created for the tool, I'm kinda dumb with Git so hopefully whatever you need is there, I developed the tool using Eclipse by the way.

https://github.com/Sneakyabc/CmangosPoolViewer

Thanks.

For Example, The Barrens Before:
barrens_before

The Barrens After:
barrens_after

### CODE REVIEW

**Comment by Tobschinski** [comment]
I'm going to have a look at it, but I need you to remove the part about spawngroups (and the linked gameobjects) before I can merge it. They have been researched carefully and are accurate data from 1.14

**Comment by al3xc1985** [comment]
@Sneakyabc can u do the same things with the herbs too?

**Comment by Sneakyabc** [comment]
@Tobschinski Do you really need to keep the spawn_group data? Much of the spawns I reviewed when creating the dataset were located right next to one of those spawn_group entries, I'm pretty confident the data from wowhead I used was pretty accurate. Having multiple different ways of managing the grouping of the mining gameobjects (using spawn_group tables as well as pooling tables) seems redundant and confusing, I think it'd be good to consolidate it into one of the methods and I personally find the pool_ tables more intuitive and easy to work with.

I could go through and convert everything to use the spawn_group method, but I'd rather not right now, haha. Regardless of if I did that I'd have to go through the data and find all of the redundant spawns I generated that conflict with the existing spawn_group entries, which would be a big pain.

When you say it was researched carefully, do you mean the locations were sniffed from the classic client? Outside of sniffing the client packets or finding a dataset on something like WoWhead I'm not sure how you'd come up with a large amount of accurate data. Some of the zones before my rework weren't so bad with the mining, but others like The Barrens and Felwood were glaringly wrong. Not trying to be a pain, but I personally don't see the value in keeping the old data if it's inconsistent and incomplete.

@al3xc1985 I could, the problems I have with doing the same with herbs would be:
1. There's WAY more herb spawns than mining nodes, so it'd be even more work
2. I did a lot of mining in WoW on retail, so I feel fairly confident I know how the spawning should feel, I can't say the same with herbalism. I'd need to do some good research to get a good idea of how common/spread the herbs should be
3. As far as I could tell from the server I was playing on, the mining nodes seemed much more inaccurate than the herbs

**Comment by al3xc1985** [comment]
@Sneakyabc I am asking this cause the herbs are by far a real problem and mess on cmangos classic part. 

Well the ideea behind their spaw groups and pooling is the same like with ores.

I hope you will take in cosideration my request

**Comment by Sneakyabc** [comment]
Hm makes sense, what would be the best path going forward then? Trying to convert my data over to use spawn_groups instead of pools would definitely be tedious, and possibly wouldn't be as accurate as the sniffed data present. But waiting until someone takes the time to sniff out every node in the game seems impractical to me as that is probably a monumental amount of work to do. I'm sure some of the existing data is sound, but some zones like The Barrens and Felwood are disasters. There's 7 mining noes in all of Felwood currently.

And if it was desired I definitely could produce something similar for the herb nodes in the game, would take some time and I'd need to do a little research to get a feel for how many herbs should be spawned around the world and a feeling for the different types' rarities.

**Comment by Tobschinski** [comment]
No, you don't have to convert anything, that is my job somewhen in the future.

**Comment by Sneakyabc** [comment]
Alright, if I removed that and pushed it as-is that'd probably create a fair number of duplicate spawns. I'll review the spawn_groups entries to see where they're at in the world and how easy it'd be to modify my includes to make it more seemless.

**Comment by Sneakyabc** [comment]
So I just want to clarify how the spawning _should_ work. Eventually we want to move to using the 'spawn_group' tables. The spawn group tables use gameobjects that are defined with id 0, and are basically just needed for their world position, the type of node they are spawned with is chosen from one of the spawn group tables that defines the possibilities and chances. The pools typically have a main type and then some more rare alternatives. Starting zones can only spawn copper, but other zones might have Mithril Deposits and according to a comment on wowhead:
"_Truesilver Veins can spawn instead of any Mithril veins. This is like a rare spawn among the veins._"

I'm curious if we know a comprehensive list of the different combinations that should be possible and their chances. I removed the spawn group stuff from my local dev environment for now but I recall all of the `spawn_group_entry` entries being the same 1 set of entries+chances repeated a bunch of times. I imagine there's probably a lot of different types of entry groups you'd need to have setup for the various parts of the world. A group for:
1. Only Copper
2. Copper + Tin (emphasis copper)
3. Copper + Tin + Silver (probably only ~5% for silver, but for the balance of copper/tin I'd be guessing)
4. Tin? + Iron + Gold
5. etc.

I feel like if we had a comprehensive list of the different combinations of nodes and their chances that should exist, you could build a pretty good dataset based on the data that's on WoWhead by pulling all of the spawns it has listed and looking at which locations have multiple types either right on top of each other or very close (within a certain distance). 

Also, should the herb nodes use the same spawn_group tables? I'd assume so.

**Comment by Tobschinski** [comment]
I have never seen 'base' ore share spawns with another one, Copper can never be Tin, Mithril never Thorium and so on.

- Copper
- Tin / Silver
- Iron / Silver / Gold
- Mithril / Gold / Truesilver
- Thorium / Truesilver

These are the 5 groups you will find in the world. The only exceptions I could find so far are: 
- Burning Steppes & Searing Gorge: Everything can also be Dark Iron
- Thousand Needles - Rustmaul Digsite: Ooze Covered Silver | Ooze Covered Gold | Ooze Covered Mithril (should be Ooze Covered Iron instead see https://github.com/cmangos/classic-db/commit/76aac8083054451a9b8c56964868d0022d9f861d)


Herbs work the same, a Plaguebloom will always be a Plaguebloom and never anything else.

**Comment by killerwife** [comment]
Can confirm. Also per my own data gathering couple additional remarks:

1. Spawn groups in vanilla were largely maxcount 1, on wotlk classic seems to have been upgraded to maxcount 2-3 even.
2. Depending on where you gather data, wotlk classic seems to share same spawn points (except ungoro crater, warning), but not cadence, respawn timers cant be trusted.
3. Be extremely weary of where you look for spawns. I am working on TBC starter zones, and I have so far found 10+ nodes that do not exist in any database, addon or otherwise.

my data
image

vs wowhead (just copper tho)

image

**Comment by Tobschinski** [comment]
> WoWhead by pulling all of the spawns it has listed and looking at which locations have multiple types either right on top of each other or very close (within a certain distance).

The reason why I don't like this approach is simply this: 
image
image (1)


Ore can be very close to each other, Herbs as well, it's not very likely for both spawns to be up at the same time, but it is possible.

**Comment by Sneakyabc** [comment]
I took a little break from working on this, partly to update my tool so it can look at data for the spawn_group entries as well.

Here's what I'm thinking with this. I don't want to create more work for you guys so, why don't I:
1) Convert the pooling inserts into spawn_group inserts
2) Try to structure my new spawn_group entries around the predefined entry-groups you guys were talking about, as well as the id = 0 method for the gameobjects
3) Once converted, looked over the spawn_groups that already exist and remove any of my stuff that seems to overlap with it (so I undo removing the data that was there without creating a bunch of duplicate spawns)

You mentioned that the groups I could expect to find are these:

1. Copper
2. Tin / Silver
3. Iron / Silver / Gold
4. Mithril / Gold / Truesilver
5. Small Thorium / Truesilver
6. Rich Thorium / Truesilver

+ a few exceptions for dark iron.

If I'm understanding this correctly, anywhere a a Tin node can spawn, a silver node can spawn in place of it. And anywhere a Silver node can spawn, it is either in a spot that can be a Tin node, or a spot that can be Iron or Gold. Yeah? You wouldn't just find a particular location that can spawn as a Silver node and nothing else?

I remember going back and looking at the wowhead data and these groups making sense based on what I saw (for instance, in the barrens I would find Tin spawns with a Silver spawn on the same exact coordinate spot, but a Copper spawn very close was not exactly on the same spot)

Would this work for you guys? Sounds like the best solution to get this finalized to me. The main thing I'd want to clarify is this:
With these sets of spawns, would the chance distribution follow something like this?:
1. Copper
2. Tin / Silver = 95/5
3. Iron / Silver / Gold = 90/5/5
4. Mithril / Gold / Truesilver 90/5/5
5. Small Thorium / Truesilver 95/5
6. Rich Thorium / Truesilver 95/5

Also, have any of you seen this before? Kinda curious, was sent it today
image

**Comment by killerwife** [comment]
https://github.com/cmangos/tbc-db/blob/master/Updates/0275_tbc_starter_zone_vein_overhaul.sql check my work on copper, tin and silver, it is largely applicable to vanilla, with its own research in corresponding zones.

**Comment by Sneakyabc** [comment]
Okay yeah that all seems to make sense and align with what I'm thinking. 
One thing: 
Is there any kind of consensus on the respawn time for different nodes? What I see currently in the classic-db is that they all are set to 5 minutes (300, 300). But each of the 3 links I've checked here for references have had different timers (yours there has 10 minutes 600, 600 - and the earlier two had either 30 minutes flat or 15 to 30 minutes). I'm guessing this is influenced by the type of node. 

Also, hey Killerwife. Long time no see. This is Sneaky. I kinda fell off the map for a while because of some changes in my life and also I forgot my login for the discord account and literally can't recover it lol

**Comment by Sneakyabc** [comment]
Also here's a conundrum... what about the more 'unique' spawn entries? Take these for example:
https://www.wowhead.com/classic/object=3763/copper-vein
https://www.wowhead.com/classic/object=3764/tin-vein

These are alternative nodes for copper and tin in the barrens that can drop blood shards. I see no alternative for silver veins, so how should these be handled? I figure either:
1. The copper and tin veins can spawn at any of these locations in place of one another
2. The two types of veins are each separate and their own thing, not sharing spawn locations but potentially sharing spawn groups
3. These alternatives can spawn in place of the normal veins and should be included in their spawn groups as options

I'd assume 2 is most likely the correct behavior

**Comment by miraco** [comment]
I guess you need to find this out on wotlk classic with testing it again again and again.

**Comment by killerwife** [comment]
I figured the nick was a big coincidence.

The ghostlands have special tin and they still share plain normal silver. And they dont share spawn group between special tin and normal tin.

Respawn is 10min and then dynamically adjusted based on pop, which ive seen go down to up to 2.5min

And yeah, i had to basically run around wotlk classic a ton.

**Comment by Sneakyabc** [comment]
Interesting, so I'm assuming in the barrens the special tin shares its spawns with normal silver as well then.

**Comment by Tobschinski** [comment]
You don't have to convert anything to spawngroups, but if you want to do a bit of rework, do smaller files. I'm not looking forward to review 50000 objects, I can tell you that.

**Comment by Sneakyabc** [comment]
I can break down the Kalimdor/EK files into 1 file for the individual zones. Also, switching to using the id = 0 method of objects and their entry should consolidate the number of entries a lot.

**Comment by killerwife** [comment]
Small warning, due to how horribly GOs were designed in the old days, pooling + gameobject_spawn_entry doesnt really always play ball. Hence it should be preferrably used only in dynguid scenarios. Should anyone want that route :D Its not even any sort of planned obsolescence, just the code sucked so much i didnt bother with pooling.

**Comment by Sneakyabc** [comment]
Haha that's pretty funny. It is very easy to convert over to spawn groups, and since pooling is deprecated I'll use spawn groups, it won't be a hassle for me. I wasn't planning on using the gameobject_spawn_entry table, I noticed the spawn_group_entry table being used in some of the links you guys sent so I figured that'd be the most appropriate to use.

One thing I noticed in my own experimentation with pooling vs spawn_groups is that objects in pools seem to respawn based on their own individual timers. If I had several objects in the same pooling table, and I mined one of them, the next one chosen to spawn would spawn instantly (assuming it had not been mined itself within its respawn timer), not after 5 minutes or whatever the respawn time was. Spawn groups did not do this, there would be a delay before the next chosen node would appear.

**Comment by Sneakyabc** [comment]
Here's another question: Would mining objects of different types ever be grouped together? For instance, would a Rich Thorium + Truesilver spot be in the same spawn group as a spot that is Small Thorium + Truesilver? Or would this not happen?

Looking at the spawn_group and spawn_group_entry tables, it seems one spawn group would need to be exclusive to one particular type of node.

**Comment by Tobschinski** [comment]
In Scarlet Monastery - GY every Kingsblood could also spawn as Gravemoss.
Other than that, no, I've never seen that happen. They are exclusive.

**Comment by Sneakyabc** [comment]
Aight, been a hot minute, update on this.

I've gone through and redone my work so that I can spawn the GOs as "id = 0" objects, making use of the `spawn_group_entry` table and using the `spawn_group` tables instead of pools. This greatly cuts down on the number of gameobjects required to look at. I've structured the spawns like was discussed so that Tin veins have a 5% chance to appear as Silver instead, Iron is 5%/5% for silver/gold, etc. 

What I want to do now is go through all of the spawns making sure nothing is unreachable, and then look at my new data compared to what is currently present in the `spawn_group` tables, and anywhere I see what looks like duplicates I'll ignore my new stuff in favor of what is already there. I'm guessing anything in the pooling tables is old and discardable and anything in the `spawn_group` tables should be more sound. 

I'm also splitting up my data so there's 1 file for each zone, not 1 file for each continent/map. 

I think we can close this pull request as this isn't what I want to submit in the end. Thanks for the feedback.

**Comment by al3xc1985** [comment]
don't forget that u pushed the warlock quest here on this pull, u need to readd that separate

**Pull request closed without merging**
