### PR TITLE
Install script improvement

### PR DESCRIPTION
**Pull request by cyberium**
Script now support
- Multiple user menu
- User settings directly modifiable in the script
- Live check of all settings
- Display status of current db
- Filling clean db from scratch with normal user (mangos user if DB already exist)
- Setting mangos user, creating and filling all data from scratch with root access
- Support of user ip limitation for mangos user
- Help to identify when db need to be updated
- Update from core folder to all DB
- Some advanced feature like delete everything if need
- Edit RealmList directly from this script no need for mysql client

### CODE REVIEW

**Comment by cyberium** [comment]
Be carefull testing this it have a lot of power and can delete all your db if you ask it to do it.

I see that to make it buildable via build script i should add some kind of switch to it.
@cala please test it on macos so we can validate current state and give me your opinion about it.

**Comment by Tobschinski** [comment]
no

**Comment by cala** [comment]
First of all, thank you very much for working on this installation script. 👍🏻 

I had a very strange behaviour on the first run. The two following errors were displayed in the command line output:
```
./InstallFullDBnew.sh: line 18: ${EXPENSION,,}: bad substitution
./InstallFullDBnew.sh: line 82: ${EXPENSION,,}: bad substitution
```
More strangely, I was then prompted by macOS that the command line tool was requesting access to:
- my personal calendars
- my contacts
- my personal pictures

I can't explain this later behaviour but that's disturbing.

Moving on with the script, I had to give root database credentials (option 2) and the script still did not auto create user mangos. Trying option 1 leads to the following errors:
```
./InstallFullDB.sh: line 519: read: -i: invalid option
read: usage: read [-ers] [-u fd] [-t timeout] [-p prompt] [-a array] [-n nchars] [-d delim] [name ...]
./InstallFullDB.sh: line 520: read: -i: invalid option
read: usage: read [-ers] [-u fd] [-t timeout] [-p prompt] [-a array] [-n nchars] [-d delim] [name ...]
./InstallFullDB.sh: line 521: read: -i: invalid option
read: usage: read [-ers] [-u fd] [-t timeout] [-p prompt] [-a array] [-n nchars] [-d delim] [name ...]
```

I think this is pointless to go further here before we sort out the first issue. :)


One side note (though an importantly one), I'm uneasy with the fact that database root credentials are requested by the script. I know we need this to create user and database and I know this has been part of our installation workflow for years.  Nonetheless, I think database security (root user) and data management (mangos user) should be kept as separate roles and that it is dangerous to mix both in the same tool. I'm well aware that most of the time CMaNGOS users hold both roles but that should be avoided and certainly not happen in a production environment. As CMaNGOS is not supposed to be used in a production environment, we can let the script as it is for now, but I think that lays ground for a security breach and is very unsafe for data.

**Comment by cyberium** [comment]
Wow, i see.. I though that you use bash like terminal in macos but it seem not going that way.

Will check if its possible to make it work.

About your remark for root access
- root access is only required for option that should create database.
- root access is not mandatory
- root access is explicitly asked when you choose option that require it
- root credentials are not saved in config file

I'll try to make it work for mac and you'll see better how it work. As it is now and considering that your first issue was at line 18 you were not able to test it properly.

**Comment by cyberium** [comment]
Can you just confirm me that you use ZSH as default shell?

**Comment by cala** [comment]
Not at all. I use bash shell nested in the Terminal.app.

**Comment by cala** [comment]
Regarding credentials: I have full confidence in you to write the script properly and handle these credentials in a secure way. 😸 
My point was not about the code quality/security, it was about having a tool that fulfills two roles that are usually kept separated for good reasons. But as I said, as long as we don't support production servers, there is nothing to really worries about.

**Comment by cala** [comment]
Tested right now on Windows 10 and this works very well as a management tool. 👍🏻

**Comment by cyberium** [comment]
Please take time when you get a chance to retest this script on your Mac.

I did made needed change to make it work natively on mac, at least it work as is on "big sur" directly in terminal.

**Comment by cyberium** [comment]
@cala reminder

**Comment by cala** [comment]
The substitution errors were removed. 👍🏻 
However, the script fails to get access to the DB:
```
Following errors should be fixed to be able to run this script:            
---------------------------------------------------------------
>>> ERROR 1045 (28000): Access denied for user 'mangos'@'localhost' (using password: YES)
>>> At least root access or user access should be possible to exit from this menu

> 1) Edit current settings to connect with normal user
> 2) Set root access to be able to create full db and normal user
> 3) Retry current settings
> 9) Exit

Please enter your choice.....: 2
```

Setting root credentials through option 2 removes the second message but error 1040 remains. I can edit the current settings through option 1 and the error remains. I have checked that the settings are correct, I have manually recreated mangos user, granted privileges, flush privileges... Nothing.

**Comment by cyberium** [comment]
Grr iam not able to reproduce nor see what can cause that.
if you are able to connect to your db with
> mysql -umangos -pmangos
check in InstallFullDB.config the user and pass to verify its correct

if all is correct then you should have something like


If not then we'll need to try to debug that together one day.

**Comment by insunaa** [comment]
what method are you using to connect to mysql? tcp or unix sockets? auth works slightly differently depending on which one you use.
if you run the command manually as cyberium said then there's a problem with the script somewhere, but if you can't login like that, try with manually setting the protocol to different things https://dev.mysql.com/doc/refman/8.0/en/connection-options.html#option_general_protocol

**Comment by cala** [comment]
@cyberium 
```
[~]$ mysql -umangos -pmangos
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'mangos'@'localhost' (using password: YES)
```
At least, this is not your script that is at fault. I'm positive that mangos user is created and has right privileges (proof: I can run the core). As @insunaa suggested, I'll test a different protocol.

**Comment by cala** [comment]
Ok, after furthermore tests, it appears that mangos user got corrupted at some point. I tried to start the core and got the same error. Last time I booted my mac, I was able to launche CMaNGOS without any problem. The only changes in the meantime were the tests for this script.

I guess the first test laid havroc to more than one place...

Anyway, I deleted the user and recreated it. Now, everything's fine and your script works.

And now, I just have to recreate the privileges for all my database that use mangos as a user...

**Comment by cyberium** [comment]
Ah thats a pain yes, 
If you tested Full installation with root password yes it delete current user if exist before recreating it.
The SQL for it is [here](https://github.com/cmangos/classic-db/pull/269/files#diff-ab3bc1ce56581f731c5d5d06f21086f83d54b3d12bbba0207f3b8db64df33accR95)
Maybe check to see if somehing look strange to you?
Didn't get any issue with it on my side.

**Comment by Muehe** [comment]
Tested this on Ubuntu 20.04 and it works well. Ran into the same problem as cala though due to using MariaDB instead of MySQL, for the record the solution was to `UPDATE mysql.user SET plugin='' WHERE user='root'; FLUSH PRIVILEGES;`.

Few notes:

* The script threw some errors when having run the script in `sql/create` manually already but not the ones in `sql/base`.
* On that note, I also think that actions requiring `root` privileges should either not be done by the script or done differently.
  * For example the rights are only required for the `sql/create` scripts, not for the `sql/base` scripts that can be run by `mangos` user. By the way the `sql/base` scripts seem sufficient to reset the DBs, no need to recreate DBs and user.
* It would probably be wise to let the mysql binary query for the password instead of exporting it as a variable, at least for `root` user.
* On a related note, the script should probably open the sql files from the core repos, instead of defining the commands itself. Create script was changed just a week ago, using the files would have caught the change, but with the script like this we'd have to replicate it.
* Also strongly in favour of adding backup and updates for characters/realmd DBs as suggested on Discord. If I don't misunderstand the only way to "update" them right now is do a full install, which also wipes all the data. :sweat_smile:

Anyway, all that can also be worked on later, as the script is already a lot better than the current one. :+1: 

Only thing I would suggest doing before merge is clarify all the warning messages where character or realm data is about to be deleted.

**Comment by Muehe** [comment]
> More strangely, I was then prompted by macOS that the command line tool was requesting access to:
> 
>     * my personal calendars
> 
>     * my contacts
> 
>     * my personal pictures
> 
> 
> I can't explain this later behaviour but that's disturbing.

Oh yeah forgot to say. This is probably due to how the core folder is being located. The script searches up to five directories up the tree from its own location, so that's probably how it touched those files (which I assume macOS will keep in your home dir). My vote on this would be to look only in `../mangos-<expansion>` and then ask if no core directory is there, or leave it up to manual config altogether.

**Comment by cyberium** [comment]
Very nice feedback Muehe (like usual with you ;) )

> Tested this on Ubuntu 20.04 and it works well. Ran into the same problem as cala though due to using MariaDB instead of MySQL, for the record the solution was to UPDATE mysql.user SET plugin='' WHERE user='root'; FLUSH PRIVILEGES;.

Iam using MariaDB too as database server currently. I didn't encoutered that issue. Maybe its because on my local pc i use mysql.exe client from mysql (not the one shipped with mariadb)
That is interesting and we need to find if that should be added by default or something. The goal should be been able to connect with any db by default without anything needed by the user.

> The script threw some errors when having run the script in sql/create manually already but not the ones in sql/base.

I'll retry that locally i tried to avoid any script error on those case but some are inevitable.

> On that note, I also think that actions requiring root privileges should either not be done by the script or done differently.
For example the rights are only required for the sql/create scripts, not for the sql/base scripts that can be run by mangos user. By the way the sql/base scripts seem sufficient to reset the DBs, no need to recreate DBs and user.

I tryed to promote the option 1 and 2 of main menu that doesn't require root access exactly for that reason.

> On a related note, the script should probably open the sql files from the core repos, instead of defining the commands itself. Create script was changed just a week ago, using the files would have caught the change, but with the script like this we'd have to replicate it.

Problem is then we cannot manage the name of the db user. The alternative is to load that sql, modify it with our username before applying it. But that is require some sheningans in bash script as bash is not so friendly language.

> It would probably be wise to let the mysql binary query for the password instead of exporting it as a variable, at least for root user.

I see your point but it will be far less pratical to enter the root password each time. So no i dont use sqlCreate sql too because i want to let the user choose the db name by himself. And i create each table individualy, meaning 8 time entering the root password,  (4 time for drop db) (4 time to create table) + 2 time for drop/create user.

> Also strongly in favour of adding backup and updates for characters/realmd DBs as suggested on Discord. If I don't misunderstand the only way to "update" them right now is do a full install, which also wipes all the data.

That would be nice yes. But that need more thinking on how to handle the backup files

> Only thing I would suggest doing before merge is clarify all the warning messages where character or realm data is about to be deleted.

Erf i would need some help there maybe with better wording

> The script searches up to five directories up the tree from its own location

Yes that is most probably why it want the calendar access. Its maybe worth to think about that more to avoid those access so script will appear less suspicious for lambda user.


Maybe iam wrong trying adding everything in same scipt? Maybe its better to have a script to install/manage db and one to update it only?
Well no i having all in same script is more usefull we should just be sure that user know when an action can delete previous data.

**Comment by cyberium** [comment]
Added backup restore feature.
Not everything rock solid and tested but should work.

If no one against i will probably merge this this week, idea is to have it tested by normal user and implement later download official backup

**Pull request closed without merging**
