### PR TITLE
[1491] Populated the Dwarven farm in #9

### PR DESCRIPTION
**Pull request by Swater96**
Added creature spawns to the Dwarven farm in #9
Used https://www.youtube.com/watch?v=leXm6STvSKM to help place mobs.

### CODE REVIEW

**Comment by Phatcat** [comment]
More cats! :3 - never can get enough cats!

**Comment by Phatcat** [comment]
I found a few more videos;
https://www.youtube.com/watch?v=mVBNh94a3Cg
https://www.youtube.com/watch?v=Oc1xijf3tb0
https://www.youtube.com/watch?v=X-PcnFvnH-o

sorry if you can't make any additional use of them.

**Comment by Swater96** [comment]
Thank you for the extra data!

**Comment by Phatcat** [comment]
I think you possibly mixing your own commits here? =)

**Comment by Phatcat** [comment]
Ahhh, you just have them both collected in the same PR. Well. Sure, you can do it like that.

**Comment by Swater96** [comment]
@cala have mercy!

**Comment by cala** [comment]
I'll try to review this soon.

**Comment by cala** [comment]
Thank both of you for this report, research and fix. This PR is closed by: https://github.com/cmangos/classic-db/commit/fb94ef48edf8ae2710c0f8f93e8137d4885ae168 and https://github.com/cmangos/classic-db/commit/8ca5e835588cb7520f7b79a30a4c7f7cbf00c60c

**Pull request closed without merging**
