### PR TITLE
Update positions for battlemasters and PvP quest NPCs

### PR DESCRIPTION
**Pull request by Daribon**
This SQL patch updates positions for battlemasters and Alliance Brigadier General/Horde Warbringers.
All Alliance Brigadier General/Horde Warbringers that have previously been missing are now spawned.

There are two sources used for this, for everything but stormwind I used Project Silvermoon Phoenix Database revision 112.
For the NPCs in Stormwind I found them in an old DB backup from 2013. I do not recall where I got the stormwind fixes from, but it came from some mangos open source DB around 2012.

Now for some images to compare from retail vanilla:
Left is after applying SQL patch.
Wow_o3s7n0bUqr

WoWScrnShot_072506_133428
WoWScrnShot_082506_161315
19 - Getting exalted with Stormpike was a big deal
WoWScrnShot_081206_122136
WoWScrnShot_071606_173402
ScreenShot_051406_222048

### CODE REVIEW

**Comment by Daribon** [comment]
Updated with fix to make Stormwind Royal Guards be in their vanilla positions, like seen in the images.

**Comment by Swater96** [comment]
Also in darn the AV master is moved from the others on the official beta
WoWScrnShot_061919_213150

**Comment by Daribon** [comment]
ye, that's included

**Comment by cala** [comment]
Thank you! All merged in https://github.com/cmangos/classic-db/commit/b2159b6e050c23333e7ceb10d8a5746cbb4d6177

**Pull request closed without merging**
