### PR TITLE
Rare Spawn Timers Update

### PR DESCRIPTION
**Pull request by Zooke**
Most data is taken as quotes from the World of Warcraft Atlas.

### CODE REVIEW

**Comment by Tobschinski** [comment]
Where does the rest come from?

**Comment by Zooke** [comment]
Educated guesses based on comments from the time, similarities to other rare spawns etc.
I can in no way claim that these timers are 100% Blizzlike, we will never know what the official timers were, but my submission is as accurate as I could research and a lot better than the data currently used.

**Comment by Zooke** [comment]
Is there anything more required of this submission to make it acceptable before I move on to their unique loot ?

**Comment by killerwife** [comment]
Zooke there is a github issue somewhere with a link to a gist with completely done rare loot. Worth talking to @MantisLord about it. Would be nice if we had same version.

**Comment by cala** [comment]
What @killerwife is refering to can be found here: https://github.com/cmangos/classic-db/issues/2. I still have it in a corner of my head but feel free to pick it if you want. 😄 

Regarding this PR, my main concern is that it is very hard to review as it currently is. All the NPCs are fixed by their guid and no name is given. Meaning that if I want to check one of them, I have to revert its ID in creature table from its guid, then check in creature_template what creature has this entry and then, I can check the spawn time from sources.

In my opinion, it would have been clearer to fix all the creatures by their ID and using the creatures' name in comment.

@Zooke Don't mind me, I do trust you: this is not your first contribution here, but good practice in open source is to check others work, at least partly, that's how we guarantee quality as a team. 😄

**Comment by Zooke** [comment]
Yep, I see your point. With 894 changes it is daunting to go through that list uncommented.
I worked from an old _npcscan file (commented with spawn times) and my submission follows the same order so it shouldn't be quite as hard as it looks for me to comment the rare names for you since I still have the file as the guide.

**Comment by Tobschinski** [comment]
I've converted 50% of that list last week, but I stopped to play more video-games.

**Comment by cala** [comment]
> Yep, I see your point. With 894 changes it is daunting to go through that list uncommented.
I worked from an old _npcscan file (commented with spawn times) and my submission follows the same order so it shouldn't be quite as hard as it looks for me to comment the rare names for you since I still have the file as the guide.

Sounds good to me, if you can spare some time on it. :+1:

**Pull request closed without merging**
